const TOTAL_NUMBER_OF_QUOTES = 2989
const TOTAL_NUMBER_OF_TRILOGIES = 3
const TOTAL_NUMBER_OF_CHARACTERS = 174

const movies = [
  'Found in all the Movies', // placeholder
  'Star Wars: Episode I – The Phantom Menace (1999)',
  'Star Wars: Episode II – Attack of the Clones (2002)',
  'Star Wars: Episode III – Revenge of the Sith (2005)',
  'Star Wars: Episode IV – A New Hope (1977)',
  'Star Wars: Episode V – The Empire Strikes Back (1980)',
  'Star Wars: Episode VI – Return of the Jedi (1983)',
  'Star Wars: Episode VII – The Force Awakens (2015)',
  'Star Wars: Episode VIII – The Last Jedi (2017)',
  'Star Wars: Episode IX – The Rise of Skywalker (2019)'
  // sequels to be added
]

const prequelsmemes = [
  { name: 'Hello There', value: 'prequelsmemes/Hello-There.gif' },
  { name: 'The High Ground', value: 'prequelsmemes/The-High-Ground.gif' },
  { name: 'I Am The Senate', value: 'prequelsmemes/I-Am-The-Senate.gif' },
  { name: "I Don't Like Sand", value: 'prequelsmemes/I-Dont-Like-Sand.gif' },
  { name: 'Only A Sith Deals In Absolutes', value: 'prequelsmemes/Only-A-Sith-Deals-In-Absolutes.gif' },
  { name: 'Now this Is Podracing!', value: 'prequelsmemes/Now-this-Is-Podracing.gif' },
  { name: 'A Surprise To Be Sure But A Welcome One', value: 'prequelsmemes/A-Surprise-To-Be-Sure-But-A-Welcome-One.gif' },
  { name: 'This Is Where The Fun Begins', value: 'prequelsmemes/This-Is-Where-The-Fun-Begins.gif' },
  { name: 'I Love Democracy', value: 'prequelsmemes/I-Love-Democracy.gif' },
  { name: 'Take A Seat, Young Skywalker', value: 'prequelsmemes/Take-A-Seat-Young-Skywalker.gif' },
  { name: 'Unlimited Power!', value: 'prequelsmemes/Unlimited-Power.gif' },
  { name: 'Do It', value: 'prequelsmemes/Do-It.gif' },
  { name: 'Another Happy Landing', value: 'prequelsmemes/Another-Happy-Landing.gif' },
  { name: 'Ironic', value: 'prequelsmemes/Ironic.gif' },
  { name: 'So Uncivilized', value: 'prequelsmemes/So-Uncivilized.gif' },
  { name: "It's Treason Then", value: 'prequelsmemes/Its-Treason-Then.gif' },
  { name: 'Liar!', value: 'prequelsmemes/Liar.gif' },
  { name: 'I Hate You!', value: 'prequelsmemes/I-Hate-You.gif' },
  { name: 'Noooooo!!', value: 'prequelsmemes/Noooooo.gif' },
  { name: 'Not Just The Men But The Women And Children Too', value: 'prequelsmemes/Not-Just-The-Men-But-The-Women-And-Children-Too.gif' },
  { name: 'The Ability To Speak Does Not Make You Intelligent', value: 'prequelsmemes/The-Ability-To-Speak-Does-Not-Make-You-Intelligent.gif' },
  { name: 'Boss Nass Head Shake', value: 'prequelsmemes/Boss-Nass-Head-Shake.gif' },
  { name: "There's Always A Bigger Fish", value: 'prequelsmemes/Theres-Always-A-Bigger-Fish.gif' },
  { name: 'I Have Brought Peace, Security etc', value: 'prequelsmemes/I-Have-Brought-Peace-Security-etc.gif' },
  { name: 'Goooooood.', value: 'prequelsmemes/Goooooood..gif' }
];


const originaltrilogymemes = [
  { name: "It's A Trap!", value: 'originaltrilogymemes/Its-A-Trap.gif' },
  { name: 'No. I Am Your Father.', value: 'originaltrilogymemes/No.-I-Am-Your-Father..gif' },
  { name: 'May The Force Be With You', value: 'originaltrilogymemes/May-The-Force-Be-With-You.gif' },
  { name: 'Do. Or Do Not. There Is No Try.', value: 'originaltrilogymemes/Do.-Or-Do-Not.-There-Is-No-Try..gif' },
  { name: "These Aren't The Droids You're Looking For", value: 'originaltrilogymemes/These-Arent-The-Droids-Youre-Looking-For.gif' },
  { name: 'I Have A Very Bad Feeling About This', value: 'originaltrilogymemes/I-Have-A-Very-Bad-Feeling-About-This.gif' },
  { name: 'Use the Force, Luke', value: 'originaltrilogymemes/Use-the-Force-Luke.gif' },
  { name: 'Why You Stuck Up...Half-Witted...Scruffy-Looking..Nerf-Herder', value: 'originaltrilogymemes/Why-You-Stuck-Up...Half-Witted...Scruffy-Looking..Nerf-Herder.gif' },
  { name: "Who's Scruffy-Looking?", value: 'originaltrilogymemes/Whos-Scruffy-Looking.gif' },
  { name: 'I Find Your Lack Of Faith Disturbing.', value: 'originaltrilogymemes/I-Find-Your-Lack-Of-Faith-Disturbing..gif' },
  { name: "That's No Moon...", value: 'originaltrilogymemes/Thats-No-Moon....gif' },
  { name: 'I Thought They Smelled Bad On The Outside', value: 'originaltrilogymemes/I-Thought-They-Smelled-Bad-On-The-Outside.gif' },
  { name: 'Laugh It Up, Fuzzball', value: 'originaltrilogymemes/Laugh-It-Up-Fuzzball.gif' },
  { name: "I Am Altering The Deal. Pray I Don't Alter It Any Further.", value: 'originaltrilogymemes/I-Am-Altering-The-Deal.-Pray-I-Dont-Alter-It-Any-Further..gif' },
  { name: "No. No. That's Not True! That's Impossible!", value: 'originaltrilogymemes/No.-No.-Thats-Not-True-Thats-Impossible.gif' },
  { name: 'Search Your Feelings. You Know It To Be True.', value: 'originaltrilogymemes/Search-Your-Feelings.-You-Know-It-To-Be-True..gif' },
  { name: 'Noooo! Noooooo!', value: 'originaltrilogymemes/Noooo-Noooooo.gif' },
  { name: "You Want This...Don't You?", value: 'originaltrilogymemes/You-Want-This...Dont-You.gif' },
  { name: 'Han Charging Down The Hall', value: 'originaltrilogymemes/Han-Charging-Down-The-Hall.gif' },
  { name: 'Now Witness The Firepower Of This Fully Armed And Operational Battle Station.', value: 'originaltrilogymemes/Now-Witness-The-Firepower.gif' },
  { name: 'Mine! Mine! Mine! Mine!', value: 'originaltrilogymemes/Mine-Mine-Mine-Mine.gif' },
  { name: 'Concentrate!', value: 'originaltrilogymemes/Concentrate.gif' },
  { name: 'Let The Hate Flow Through You', value: 'originaltrilogymemes/Let-The-Hate-Flow-Through-You.gif' },
  { name: 'Goood...I Can Feel Your Anger', value: 'originaltrilogymemes/Goood...I-Can-Feel-Your-Anger.gif' },
  { name: 'You Will Find That It Is You Who Are Mistaken...About A Great...Many...Things.', value: 'originaltrilogymemes/You-Will-Find-That-It-Is-You-Who-Are-Mistaken.gif' }
];

const sequelsmemes = [
  { name: 'More....More!', value: 'sequelsmemes/More....More.gif' },
  { name: 'Somehow Palpatine Returned', value: 'sequelsmemes/Somehow-Palpatine-Returned.gif' },
  { name: "That's Not How The Force Works!", value: 'sequelsmemes/Thats-Not-How-The-Force-Works.gif' },
  { name: 'They fly now?', value: 'sequelsmemes/They-fly-now.gif' },
  { name: 'Rey Skywalker', value: 'sequelsmemes/Rey-Skywalker.gif' },
  { name: 'Luke Throwing Away Lightsaber', value: 'sequelsmemes/Luke-Throwing-Away-Lightsaber.gif' },
  { name: 'Leia Flying Through Space', value: 'sequelsmemes/Leia-Flying-Through-Space.gif' },
  { name: 'Traitor!', value: 'sequelsmemes/Traitor.gif' },
  { name: 'REY!!!!', value: 'sequelsmemes/REY.gif' },
  { name: 'Ben Swolo', value: 'sequelsmemes/Ben-Swolo.gif' },
  { name: 'I Am All The Sith', value: 'sequelsmemes/I-Am-All-The-Sith.gif' },
  { name: 'I Am All The Jedi', value: 'sequelsmemes/I-Am-All-The-Jedi.gif' },
  { name: 'Crossguard Saber Meme', value: 'sequelsmemes/Crossguard-Saber-Meme.gif' },
  { name: 'Luke Drinking Milk', value: 'sequelsmemes/Luke-Drinking-Milk.gif' },
  { name: 'The Sacred Jedi Texts!', value: 'sequelsmemes/The-Sacred-Jedi-Texts.gif' },
  { name: 'Every Word Of What You Just Said Was Wrong', value: 'sequelsmemes/Every-Word-Of-What-You-Just-Said-Was-Wrong.gif' },
  { name: "No one's ever really gone", value: 'sequelsmemes/No-ones-ever-really-gone.gif' },
  { name: 'I Like This Thing!', value: 'sequelsmemes/I-Like-This-Thing.gif' },
  { name: "Chewie, We're Home", value: 'sequelsmemes/Chewie-Were-Home.gif' },
  { name: 'The Holdo Maneuver', value: 'sequelsmemes/The-Holdo-Maneuver.webp' }
];

const characters = new Map([
  ['Sheev Palpatine', 'Palpatine'], // array of Actor choices //left being choices that appear
  ['Luke Skywalker', 'Luke Skywalker'],
  ['Anakin Skywalker', 'Anakin Skywalker'],
  ['Mace Windu', 'Mace Windu'],
  ['Padme Amidala', 'Padme Amidala'],
  ['Obi-Wan Kenobi', 'Obi-Wan Kenobi'],
  ['Qui-Gon Jinn', 'Qui-Gon Jinn'],
  ['Princess Leia', 'Princess Leia'],
  ['Lando Calrissian', 'Lando Calrissian'],
  ['Sabé', 'Queen Amidala'],
  ['Grandmaster Yoda', 'Yoda'],
  ['Ben Kenobi', 'Ben Kenobi'],
  ['Grand Moff Tarkin', 'Grand Moff Tarkin'],
  ['Darth Sidious', 'Darth Sidious'],
  ['Han Solo', 'Han Solo'],
  ['Hermit Yoda', 'Hermit Yoda'],
  ['General Grievous', 'General Grievous'],
  ['Count Dooku', 'Count Dooku'],
  ['Nute Gunray', 'Nute Gunray'],
  ['Wedge Antilles', 'Wedge Antilles'],
  ['Darth Vader', 'Darth Vader'],
  ['Admiral Ackbar', 'Admiral Ackbar'],
  ['C-3PO', 'C-3PO'],
  ['Biggs Darklighter', 'Biggs Darklighter'],
  ['Gregar Typho', 'Gregar Typho'],
  ['Watto', 'Watto'],
  ['Bail Organa', 'Bail Organa'],
  ['Greedo', 'Greedo'],
  ['Jango Fett', 'Jango Fett'],
  ['GH-7 Medical Droid', 'Medical Droid'],
  ['Lama Su', 'Lama Su'],
  ['Jar Jar Binks', 'Jar Jar Binks'],
  ['Shmi Skywalker', 'Shmi Skywalker'],
  ['FodeandBeed', 'FodeandBeed'],
  ['Tuan We', 'Tuan We'],
  ['Jocasta Nu', 'Jocasta Nu'],
  ['Mas Amedda', 'Mas Amedda'],
  ['Boss Nass', 'Boss Nass'],
  ['Dexter Jettster', 'Dexter Jettster'],
  ['Rune Hakko', 'Rune Hakko'],
  ['J.K. Burtola', 'J.K. Burtola'],
  ['Ki-Adi-Mundi', 'Ki-Adi-Mundi'],
  ['Quarsh Panaka', 'Quarsh Panaka'],
  ['Darth Maul', 'Darth Maul'],
  ['Elan Sleazebaggano', 'Elan Sleazebaggano'],
  ['Mon Mothma', 'Mon Mothma'],
  ['Bravo Two', 'Bravo Two'],
  ['Giddean Danu', 'Giddean Danu'],
  ['Sors Bandeam', 'Sors Bandeam'],
  ['Sebulba', 'Sebulba'],
  ['Jabba the Hutt', 'Jabba the Hutt'],
  ['Poggle the Lesser', 'Poggle the Lesser'],
  ['Kitster', 'Kitster'],
  ['Cliegg Lars', 'Cliegg Lars'],
  ['Roos Tarpals', 'Roos Tarpals'],
  ['Wald', 'Wald'],
  ['Finus Valorum', 'Finus Valorum'],
  ['Raymus Antilles', 'Raymus Antilles'],
  ['Stormtrooper', 'Stormtrooper'],
  ['Gunnery Captain Bolvan', 'Gunnery Captain Bolvan'],
  ['Daine Jir', 'Daine Jir'],
  ['Commander Praji', 'Commander Praji'],
  ['Beru Whitesun Lars', 'Beru Whitesun Lars'],
  ['Owen Lars', 'Owen Lars'],
  ['Cassio Tagge', 'Cassio Tagge'],
  ['Conan Antonio Motti', 'Conan Antonio Motti'],
  ['Wuher', 'Wuher'],
  ['Ponda Baba', 'Ponda Baba'],
  ['Doctor Cornelius Evazan', 'Doctor Cornelius Evazan'],
  ['Chewbacca', 'Chewbacca'],
  ['Siward Cass', 'Siward Cass'],
  ['Captain Khurgee', 'Captain Khurgee'],
  ['Gantry Officer', 'Gantry Officer'],
  ['Vanden Willard', 'Vanden Willard'],
  ['Gold Leader(Jon Vander)', 'Gold Leader(Jon Vander)'],
  ['Jan Dodonna', 'Jan Dodonna'],
  ['Red Leader(Garven Dreis)', 'Red Leader(Garven Dreis)'],
  ['Lieutenant Tanbris', 'Lieutenant Tanbris'],
  ['Jek Tono Porkins', 'Jek Tono Porkins'],
  ['Del Goren', 'Del Goren'],
  ['Gold Five(Davish "Pops" Krail)', 'Gold Five(Davish "Pops" Krail)'],
  ['Yavin Base Controller', 'Yavin Base Controller'],
  ['(Mauler)Mithel', '(Mauler)Mithel'],
  ['Carlist Rieekan', 'Carlist Rieekan'],
  ['Deck Officer(Tamizander Rey)', 'Deck Officer(Tamizander Rey)'],
  ['Lieutenant Cal Alder', 'Lieutenant Cal Alder'],
  ['Major Bren Derlin', 'Major Bren Derlin'],
  ['Zev Senesca', 'Zev Senesca'],
  ['Firmus Piett', 'Firmus Piett'],
  ['Maximilian Veers', 'Maximilian Veers'],
  ['Kendal Ozzel', 'Kendal Ozzel'],
  ['Dak Ralter', 'Dak Ralter'],
  ['Colonel Ledick Firest', 'Colonel Ledick Firest'],
  ['R2-D2', 'R2-D2'],
  ['Lorth Needa', 'Lorth Needa'],
  ['Commander Nemet', 'Commander Nemet'],
  ['Boba Fett', 'Boba Fett'],
  ['Captain Bewil', 'Captain Bewil'],
  ['Moff Tiaan Jerjerrod', 'Moff Tiaan Jerjerrod'],
  ['TT-8LorY7 Gatekeeper Droid', 'TT-8LorY7 Gatekeeper Droid'],
  ['Salacious B. Crumb', 'Salacious B. Crumb'],
  ['Bib Fortuna', 'Bib Fortuna'],
  ['EV-9D9', 'EV-9D9'],
  ['Sy Snootles', 'Sy Snootles'],
  ['General Crix Madine', 'General Crix Madine'],
  ['Scout Trooper', 'Scout Trooper'],
  ['Commander Igar', 'Commander Igar'],
  ['Colonel Dyer', 'Colonel Dyer'],
  ['AT-ST Pilot', 'AT-ST Pilot'],
  ['George Lucas', 'George Lucas'],
  ['Lor San Tekka', 'Lor San Tekka'],
  ['Poe Dameron', 'Poe Dameron'],
  ['Kylo Ren', 'Kylo Ren'],
  ['Captain Phasma', 'Captain Phasma'],
  ['Unkar Plutt', 'Unkar Plutt'],
  ['Rey', 'Rey'],
  ['Lawrence Kasdan & J.J. Abrams and Michael Arndt', 'Lawrence Kasdan & J.J. Abrams and Michael Arndt'],
  ['Finn', 'Finn'],
  ['Armitage Hux', 'Armitage Hux'],
  ['Nastia Unamo', 'Nastia Unamo'],
  ['Dopheld Mitaka', 'Dopheld Mitaka'],
  ['Bala-Tik', 'Bala-Tik'],
  ['Tasu Leech', 'Tasu Leech'],
  ['Supreme Leader Snoke', 'Supreme Leader Snoke'],
  ['Maz Kanata', 'Maz Kanata'],
  ['Bazine Netal', 'Bazine Netal'],
  ['Young Rey', 'Young Rey'],
  ['Stormtrooper(First Order)', 'Stormtrooper(First Order)'],
  ['Harter Kalonia', 'Harter Kalonia'],
  ['Temmin "Snap" Wexley', 'Temmin "Snap" Wexley'],
  ['Major Ematt', 'Major Ematt'],
  ['Ushos O. Statura', 'Ushos O. Statura'],
  ['Vober Dand', 'Vober Dand'],
  ['Tabala Zo', 'Tabala Zo'],
  ['Jessika Pava', 'Jessika Pava'],
  ['Yolo Ziff', 'Yolo Ziff'],
  ['Lieutenant Rodinon', 'Lieutenant Rodinon'],
  ['Resistance Medic', 'Resistance Medic'],
  ['Rian Johnson', 'Rian Johnson'],
  ['Edrison Peavey', 'Edrison Peavey'],
  ['Moden Canady', 'Moden Canady'],
  ['Tallissan Lintra','Tallissan Lintra'],
  ['Larma D\'Acy','Larma D\'Acy'],
  ['Amilyn Holdo','Amilyn Holdo'],
  ['Rose Tico', 'Rose Tico'],
  ['Canto Bight Police Department(CBPD)','Canto Bight Police Department(CBPD)'],
  ['DJ(Don\'t Join)','DJ(Don\'t Join)'],
  ['Temiri Blagg','Temiri Blagg'],
  ['First Order Officer', 'First Order Officer'],
  ['(Salty)Sharp','(Salty)Sharp'],
  ['Kaydel Ko Connix','Kaydel Ko Connix'],
  ['Oniho Zaya','Oniho Zaya'],
  ['J.J. Abrams & Chris Terrio', 'J.J. Abrams & Chris Terrio'],
  ['Boolio', 'Boolio'],
  ['Beaumont Kin','Beaumont Kin'],
  ['Enric Pryde', 'Enric Pryde'],
  ['Tishra Kandia', 'Tishra Kandia'],
  ['Zorii Bliss','Zorii Bliss'],
  ['D-O', 'D-O'],
  ['Babu Frik','Babu Frik'],
  ['Miramir','Miramir'],
  ['Dathan','Dathan'],
  ['Jannah','Jannah'],
  ['Dark Rey','Dark Rey'],
  ['Ben Solo', 'Ben Solo'],
  ['Milon Lenwith','Milon Lenwith'],
  ['Masir Trach','Masir Trach'],
  ['Frantis Griss','Frantis Griss'],
  ['Ahsoka Tano','Ahsoka Tano'],
  ['Kanan Jarrus','Kanan Jarrus'],
  ['Luminara Unduli','Luminara Unduli'],
  ['Aayla Secura','Aayla Secura'],
  ['Adi Gallia','Adi Gallia'],
  ['Tatooine Elder','Tatooine Elder']
])

const actorPictures = new Map([
  ['Palpatine',
    'https://4.bp.blogspot.com/-CY9BB38dzss/VD25QaYDgmI/AAAAAAAAEqE/AhmiSvwndM0/s1600/Palp_trustme.jpg'],
  ['Gregar Typho',
    'webp'],
  ['Watto',
    'webp'],
  ['Anakin Skywalker',
    'webp'],
  ['Mace Windu',
    'webp'],
  ['Padme Amidala',
    'http://1.bp.blogspot.com/-P9QYCyNW3NQ/T-YSoELg6kI/AAAAAAAADWw/Wtw2OtLcN7w/s1600/Padme+17.jpg'],
  ['Obi-Wan Kenobi',
    'webp'],
  ['Qui-Gon Jinn',
    'webp'],
  ['Bail Organa',
    'webp'],
  ['Greedo',
    'webp'],
  ['Jango Fett',
    'webp'],
  ['Medical Droid',
    'jpeg'],
  ['Queen Amidala',
    'webp'],
  ['Yoda',
    'webp'],
  ['Lama Su',
    'webp'],
  ['Jar Jar Binks',
    'https://upload.wikimedia.org/wikipedia/en/4/4b/Jjportrait.jpg'],
  ['Shmi Skywalker',
    'webp'],
  ['Darth Sidious',
    'jpg'],
  ['FodeandBeed',
    'jpeg'],
  ['Tuan We',
    'jpeg'],
  ['Jocasta Nu',
    'jpeg'],
  ['Mas Amedda',
    'webp'],
  ['Boss Nass',
    'webp'],
  ['Dexter Jettster',
    'webp'],
  ['Rune Hakko',
    'webp'],
  ['J.K. Burtola',
    'webp'],
  ['General Grievous',
    'webp'],
  ['Count Dooku',
    'webp'],
  ['Ki-Adi-Mundi',
    'webp'],
  ['Nute Gunray',
    'webp'],
  ['Quarsh Panaka',
    'webp'],
  ['Darth Maul',
    'webp'],
  ['Elan Sleazebaggano',
    'webp'],
  ['Darth Vader',
    'webp'],
  ['Mon Mothma',
    'webp'],
  ['Bravo Two',
    'webp'],
  ['C-3PO',
    'webp'],
  ['Giddean Danu',
    'webp'],
  ['Sors Bandeam',
    'webp'],
  ['Sebulba',
    'webp'],
  ['Jabba the Hutt',
    'jpeg'],
  ['Poggle the Lesser',
    'jpg'],
  ['Kitster',
    'webp'],
  ['Cliegg Lars',
    'jpeg'],
  ['Roos Tarpals',
    'webp'],
  ['Wald',
    'webp'],
  ['Finus Valorum',
    'https://i.pinimg.com/originals/29/16/62/29166227119bf6376119c9d89c3d88c7.jpg'],
  ['Raymus Antilles',
    'webp'],
  ['Stormtrooper',
    'webp'],
  ['Gunnery Captain Bolvan',
    'webp'],
  ['Biggs Darklighter',
    'webp'],
  ['Princess Leia',
    'webp'],
  ['Daine Jir',
    'webp'],
  ['Commander Praji',
    'webp'],
  ['Luke Skywalker',
    'webp'],
  ['Beru Whitesun Lars',
    'webp'],
  ['Owen Lars',
    'webp'],
  ['Ben Kenobi',
    'https://upload.wikimedia.org/wikipedia/en/3/32/Ben_Kenobi.png'],
  ['Cassio Tagge',
    'webp'],
  ['Grand Moff Tarkin',
    'webp'],
  ['Conan Antonio Motti',
    'webp'],
  ['Wuher',
    'webp'],
  ['Ponda Baba',
    'webp'],
  ['Doctor Cornelius Evazan',
    'webp'],
  ['Han Solo',
    'webp'],
  ['Chewbacca',
    'webp'],
  ['Siward Cass',
    'webp'],
  ['Captain Khurgee',
    'webp'],
  ['Gantry Officer',
    'webp'],
  ['Vanden Willard',
    'webp'],
  ['Gold Leader(Jon Vander)',
    'webp'],
  ['Jan Dodonna',
    'webp'],
  ['Wedge Antilles',
    'https://upload.wikimedia.org/wikipedia/en/4/41/Wedge_Antilles-Denis_Lawson-Star_Wars_%281977%29.jpg'],
  ['Red Leader(Garven Dreis)',
    'webp'],
  ['Lieutenant Tanbris',
    'webp'],
  ['Jek Tono Porkins',
    'webp'],
  ['Del Goren',
    'webp'],
  ['Gold Five(Davish "Pops" Krail)',
    'webp'],
  ['Yavin Base Controller',
    'webp'],
  ['(Mauler)Mithel',
    'webp'],
  ['Carlist Rieekan',
    'webp'],
  ['Deck Officer(Tamizander Rey)',
    'webp'],
  ['Lieutenant Cal Alder',
    'webp'],
  ['Major Bren Derlin',
    'webp'],
  ['Zev Senesca',
    'webp'],
  ['Firmus Piett',
    'webp'],
  ['Maximilian Veers',
    'webp'],
  ['Kendal Ozzel',
    'webp'],
  ['Dak Ralter',
    'webp'],
  ['Colonel Ledick Firest',
    'webp'],
  ['R2-D2',
    'webp'],
  ['Hermit Yoda',
    'webp'],
  ['Lorth Needa',
    'webp'],
  ['Commander Nemet',
    'webp'],
  ['Lando Calrissian',
    'webp'],
  ['Boba Fett',
    'webp'],
  ['Captain Bewil',
    'webp'],
  ['Moff Tiaan Jerjerrod',
    'webp'],
  ['TT-8LorY7 Gatekeeper Droid',
    'webp'],
  ['Salacious B. Crumb',
    'webp'],
  ['Bib Fortuna',
    'webp'],
  ['EV-9D9',
    'webp'],
  ['Sy Snootles',
    'webp'],
  ['Admiral Ackbar',
    'webp'],
  ['General Crix Madine',
    'webp'],
  ['Scout Trooper',
    'webp'],
  ['Commander Igar',
    'webp'],
  ['Colonel Dyer',
    'webp'],
  ['AT-ST Pilot',
    'webp'],
  ['George Lucas',
    'webp'],
  ['Lor San Tekka',
    'webp'],
  ['Poe Dameron',
    'webp'],
  ['Kylo Ren',
    'https://cdn.mos.cms.futurecdn.net/8RRXRpNMcgJSNGQbizo3sf.jpg'],
  ['Captain Phasma',
    'webp'],
  ['Unkar Plutt',
    'webp'],
  ['Rey',
    'webp'],
  ['Lawrence Kasdan & J.J. Abrams and Michael Arndt',
    'https://www.wga.org/uploadedImages/craft/Arndt-Kasdan-Abrams.jpg'],
  ['Finn',
    'https://upload.wikimedia.org/wikipedia/en/2/2a/Finn-Force_Awakens_%282015%29.png'],
  ['Armitage Hux',
    'webp'],
  ['Nastia Unamo',
    'webp'],
  ['Dopheld Mitaka',
    'webp'],
  ['Bala-Tik',
    'webp'],
  ['Tasu Leech',
    'webp'],
  ['Supreme Leader Snoke',
    'webp'],
  ['Maz Kanata',
    'https://upload.wikimedia.org/wikipedia/en/6/65/Maz_Kanata-Force_Awakens.jpg'],
  ['Bazine Netal',
    'webp'],
  ['Young Rey',
    'webp'],
  ['Stormtrooper(First Order)',
    'webp'],
  ['Harter Kalonia',
    'webp'],
  ['Temmin "Snap" Wexley',
    'webp'],
  ['Major Ematt',
    'webp'],
  ['Ushos O. Statura',
    'webp'],
  ['Vober Dand',
    'webp'],
  ['Tabala Zo',
    'webp'],
  ['Jessika Pava',
    'webp'],
  ['Yolo Ziff',
    'webp'],
  ['Lieutenant Rodinon',
    'webp'],
  ['Resistance Medic',
    'webp'],
  ['Rian Johnson',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Star_Wars-_The_Last_Jedi_Japan_Premiere_Red_Carpet-_Rian_Johnson_%2838905282292%29_%28cropped%29.jpg/1280px-Star_Wars-_The_Last_Jedi_Japan_Premiere_Red_Carpet-_Rian_Johnson_%2838905282292%29_%28cropped%29.jpg'],
  ['Edrison Peavey',
    'webp'],
  ['Moden Canady',
    'webp'],
  ['Tallissan Lintra',
    'webp'],
  ['Larma D\'Acy',
    'webp'],
  ['Amilyn Holdo',
    'webp'],
  ['Rose Tico',
    'https://upload.wikimedia.org/wikipedia/en/f/f3/Rose_Tico_from_The_Last_Jedi.jpg'],
  ['Canto Bight Police Department(CBPD)',
    'webp'],
  ['DJ(Don\'t Join)',
    'webp'],
  ['Temiri Blagg',
    'webp'],
  ['First Order Officer',
    'webp'],
  ['(Salty)Sharp',
    'webp'],
  ['Kaydel Ko Connix',
    'webp'],
  ['Oniho Zaya',
    'webp'],
  ['J.J. Abrams & Chris Terrio',
    'webp'],
  ['Boolio',
    'webp'],
  ['Beaumont Kin',
    'webp'],
  ['Enric Pryde',
    'webp'],
  ['Tishra Kandia',
    'webp'],
  ['Zorii Bliss',
    'webp'],
  ['D-O',
    'webp'],
  ['Babu Frik',
    'webp'],
  ['Miramir',
    'webp'],
  ['Dathan',
    'webp'],
  ['Jannah',
    'webp'],
  ['Dark Rey',
    'jpg'],
  ['Ben Solo',
    'webp'],
  ['Milon Lenwith',
    'webp'],
  ['Masir Trach',
    'webp'],
  ['Frantis Griss',
    'webp'],
  ['Ahsoka Tano',
    'webp'],
  ['Kanan Jarrus',
    'webp'],
  ['Luminara Unduli',
    'webp'],
  ['Aayla Secura',
    'webp'],
  ['Adi Gallia',
    'webp'],
  ['Tatooine Elder',
    'webp']
  
])

module.exports = {
  movies,
  characters,
  actorPictures,
  TOTAL_NUMBER_OF_QUOTES,
  TOTAL_NUMBER_OF_CHARACTERS,
  TOTAL_NUMBER_OF_TRILOGIES,
  prequelsmemes,
  originaltrilogymemes,
  sequelsmemes
}
