const rengar = ["aksdnaklsf"];
const actors = ['Palpatine',
  'Gregar Typho',
  'Watto',
  'Anakin Skywalker',
  'Mace Windu',
  'Padme Amidala',
  'Obi-Wan Kenobi',
  'Qui-Gon Jinn',
  'Bail Organa',
  'Greedo',
  'Jango Fett',
  'Medical Droid',
  'Queen Amidala',
  'Yoda',
  'Lama Su',
  'Jar Jar Binks',
  'Shmi Skywalker',
  'Darth Sidious',
  'Fode/Beed',
  'Tuan We',
  'Jocasta Nu',
  'Mas Amedda',
  'Boss Nass',
  'Dexter Jettster',
  'Rune Hakko',
  'Jedi Child Jack',
  'General Grievous',
  'Count Dooku',
  'Ki-Adi-Mundi',
  'Nute Gunray',
  'Quarsh Panaka',
  'Darth Maul',
  'Elan Sleazebaggano',
  'Narrator',
  'Darth Vader',
  'Mon Mothma',
  'Bravo Two',
  'C-3PO',
  'Giddean Danu',
  'Sors Bandeam',
  'Sebulba',
  'Jabba the Hutt',
  'Poggle the Lesser',
  'Kitster',
  'Cliegg Lars',
  'Roos Tarpals',
  'Wald',
  'Finus Valorum'];
module.exports = {rengar, actors}
