const TOTAL_NUMBER_OF_QUOTES = 690;
const LAST_ID_OF_FIRST_MOVIE = 281;
const LAST_ID_OF_SECOND_MOVIE = 429;
const LAST_ID_OF_THIRD_MOVIE = 690;

const movies =[
              "Found in all the Movies",
              "Star Wars: Episode I – The Phantom Menace (1999)",
              "Star Wars: Episode II – Attack of the Clones (2002)",
              "Star Wars: Episode III – Revenge of the Sith (2005)"
]
const actors = [['Palpatine','Palpatine'],
['Watto','Watto'],
['Anakin Skywalker','Anakin Skywalker'],
['Mace Windu','Mace Windu'],
['Padme Amidala','Padme Amidala'],
['Obi-Wan Kenobi','Obi-Wan Kenobi'],
['Qui-Gon Jinn','Qui-Gon Jinn'],
['Greedo','Greedo'],
['Jango Fett','Jango Fett'],
['Queen Amidala','Queen Amidala'],
['Yoda','Yoda'],
['Jar Jar Binks', 'Jar Jar Binks'],
['Shmi Skywalker', 'Shmi Skywalker'],
['Darth Sidious', 'Darth Sidious'],
['Boss Nass','Boss Nass'],
['Jedi Child Jack','Jedi Child Jack'],
['General Grievous','General Grievous'],
['Count Dooku','Count Dooku'],
['Nute Gunray','Nute Gunray'],
['Darth Maul','Darth Maul'],
['Darth Vader','Darth Vader'],
['Mon Mothma','Mon Mothma'],
['C-3PO','C-3PO'],
['Jabba the Hutt','Jabba the Hutt'],
];
// const actors = [['Palpatine','Palpatine'],
// ['Gregar Typho','Gregar Typho'],
// ['Watto','Watto'],
// ['Anakin Skywalker','Anakin Skywalker'],
// ['Mace Windu','Mace Windu'],
// ['Padme Amidala','Padme Amidala'],
// ['Obi-Wan Kenobi','Obi-Wan Kenobi'],
// ['Qui-Gon Jinn','Qui-Gon Jinn'],
// ['Bail Organa','Bail Organa'],
// ['Greedo','Greedo'],
// ['Jango Fett','Jango Fett'],
// ['Medical Droid','Medical Droid'],
// ['Queen Amidala','Queen Amidala'],
// ['Yoda','Yoda'],
// ['Lama Su','Lama Su'],
// ['Jar Jar Binks', 'Jar Jar Binks'],
// ['Shmi Skywalker', 'Shmi Skywalker'],
// ['Darth Sidious', 'Darth Sidious'],
// ['Fode/Beed','Fode/Beed'],
// ['Tuan We','Tuan We'],
// ['Jocasta Nu','Jocasta Nu'],
// ['Mas Amedda','Mas Amedda'],
// ['Boss Nass','Boss Nass'],
// ['Dexter Jettster','Dexter Jettster'],
// ['Rune Hakko','Rune Hakko'],
// ['Jedi Child Jack','Jedi Child Jack'],
// ['General Grievous','General Grievous'],
// ['Count Dooku','Count Dooku'],
// ['Ki-Adi-Mundi','Ki-Adi-Mundi'],
// ['Nute Gunray','Nute Gunray'],
// ['Quarsh Panaka','Quarsh Panaka'],
// ['Darth Maul','Darth Maul'],
// ['Elan Sleazebaggano', 'Elan Sleazebaggano'],
// ['Narrator','Narrator'],
// ['Darth Vader','Darth Vader'],
// ['Mon Mothma','Mon Mothma'],
// ['Bravo Two', 'Bravo Two'],
// ['C-3PO','C-3PO'],
// ['Giddean Danu','Giddean Danu'],
// ['Sors Bandeam','Sors Bandeam'],
// ['Sebulba','Sebulba'],
// ['Jabba the Hutt','Jabba the Hutt'],
// ['Poggle the Lesser','Poggle the Lesser'],
// ['Kitster','Kitster'],
// ['Cliegg Lars','Cliegg Lars'],
// ['Roos Tarpals','Roos Tarpals'],
// ['Wald','Wald'],
// ['Finus Valorum','Finus Valorum']];

module.exports = {
                  movies,
                  actors,
                  TOTAL_NUMBER_OF_QUOTES,
                  LAST_ID_OF_FIRST_MOVIE,
                  LAST_ID_OF_SECOND_MOVIE,
                  LAST_ID_OF_THIRD_MOVIE
                }
